import { AbsoluteFill, Sequence, staticFile } from 'remotion';
import { Intro, Outro, ScreenFrame, Caption, Highlight } from '@videodoc/core';
import { useVoiceover } from '@videodoc/core/voiceover';
import { theme } from '../theme.js';

// Screenshots live in docs-output/screenshots/auth-flow/.
// publicDir=docs-output/ so staticFile() paths are relative to that dir.
const ss = (name) => staticFile(`screenshots/auth-flow/${name}.png`);
const STEP = 90; // 3s per step at 30fps

export const AuthFlow = ({ appName = 'Mealtime' }) => {
  // Loads docs-output/audio/AuthFlow-voiceover.mp3 (generated by docs:voiceover).
  // Renders nothing if the file is missing — safe to use without TTS credentials.
  const { VoiceoverAudio } = useVoiceover();

  return (
    <AbsoluteFill style={{ background: theme.background }}>
      <VoiceoverAudio />

      <Sequence from={0} durationInFrames={STEP}>
        <Intro
          appName={appName}
          title="Como fazer login"
          description="Tutorial rápido do fluxo de autenticação."
          theme={theme}
        />
      </Sequence>

      <Sequence from={STEP} durationInFrames={STEP}>
        <ScreenFrame src={ss('01-landing')} theme={theme} />
        <Caption text="Acesse o site e localize a opção de entrar." theme={theme} />
      </Sequence>

      <Sequence from={STEP * 2} durationInFrames={STEP}>
        <ScreenFrame src={ss('02-login-screen')} theme={theme} />
        <Highlight x={560} y={320} width={160} height={48} theme={theme} />
        <Caption text="Na tela de login, informe e-mail e senha." theme={theme} />
      </Sequence>

      <Sequence from={STEP * 3} durationInFrames={STEP}>
        <ScreenFrame src={ss('03-form-filled')} theme={theme} />
        <Caption text="Clique em Entrar para acessar sua conta." theme={theme} />
      </Sequence>

      <Sequence from={STEP * 4} durationInFrames={STEP}>
        <Outro message="Pronto! Você já está dentro." theme={theme} />
      </Sequence>
    </AbsoluteFill>
  );
};
