import { AbsoluteFill, Sequence, staticFile, useVideoConfig } from 'remotion';
import { Intro, Outro, ScreenFrame, Caption, Highlight } from '@videodoc/core';
import { mergeTheme } from '@videodoc/core/theme';
import { useVoiceover } from '@videodoc/core/voiceover';
import { theme } from '../theme.js';

// Screenshots live in docs-output/screenshots/auth-flow/.
// publicDir=docs-output/ so staticFile() paths are relative to that dir.
const ss = (name) => staticFile(`screenshots/auth-flow/${name}.png`);
const STEP = 90; // 3s per step at 30fps
const BASE_CANVAS = { width: 1280, height: 720 };
const BASE_LOGIN_HIGHLIGHT = { x: 560, y: 320, width: 160, height: 48 };

const scaleRectFromBaseline = (videoWidth, videoHeight, rect) => {
  const scale = Math.min(videoWidth / BASE_CANVAS.width, videoHeight / BASE_CANVAS.height);
  const offsetX = (videoWidth - BASE_CANVAS.width * scale) / 2;
  const offsetY = (videoHeight - BASE_CANVAS.height * scale) / 2;

  return {
    x: offsetX + rect.x * scale,
    y: offsetY + rect.y * scale,
    width: rect.width * scale,
    height: rect.height * scale,
  };
};

export const AuthFlow = ({ appName = 'Mealtime', brand = {} }) => {
  // Loads docs-output/audio/AuthFlow-voiceover.mp3 (generated by docs:voiceover).
  // Renders nothing if the file is missing — safe to use without TTS credentials.
  const { VoiceoverAudio } = useVoiceover();
  const { width: videoWidth, height: videoHeight } = useVideoConfig();
  const flowTheme = mergeTheme({
    ...theme,
    ...(brand?.colors ?? {}),
  });
  const loginHighlight = scaleRectFromBaseline(videoWidth, videoHeight, BASE_LOGIN_HIGHLIGHT);

  return (
    <AbsoluteFill style={{ background: flowTheme.background }}>
      <VoiceoverAudio />

      <Sequence from={0} durationInFrames={STEP}>
        <Intro
          appName={appName}
          logo={brand?.assets?.logo}
          title="Como fazer login"
          description="Tutorial rápido do fluxo de autenticação."
          theme={flowTheme}
        />
      </Sequence>

      <Sequence from={STEP} durationInFrames={STEP}>
        <ScreenFrame src={ss('01-landing')} theme={flowTheme} />
        <Caption text="Acesse o site e localize a opção de entrar." theme={flowTheme} />
      </Sequence>

      <Sequence from={STEP * 2} durationInFrames={STEP}>
        <ScreenFrame src={ss('02-login-screen')} theme={flowTheme} />
        <Highlight
          x={loginHighlight.x}
          y={loginHighlight.y}
          width={loginHighlight.width}
          height={loginHighlight.height}
          theme={flowTheme}
        />
        <Caption text="Na tela de login, informe e-mail e senha." theme={flowTheme} />
      </Sequence>

      <Sequence from={STEP * 3} durationInFrames={STEP}>
        <ScreenFrame src={ss('03-form-filled')} theme={flowTheme} />
        <Caption text="Clique em Entrar para acessar sua conta." theme={flowTheme} />
      </Sequence>

      <Sequence from={STEP * 4} durationInFrames={STEP}>
        <Outro message="Pronto! Você já está dentro." theme={flowTheme} />
      </Sequence>
    </AbsoluteFill>
  );
};
